HBSD: Incorporate select changes from a French firewall vendor
Though this commit isn't tested, this brings in some select changes from
a French firewall vendor. In this commit, I've made their changes
generic such that anyone basing their work on this can do so with
minimal changes downstream.

I'm 100% sure further refinement is necessary. However, this provides a
good starting place for further testing and refinement. As we (at
${DAYJOB}, the sponsor of this work) work on integration with the other
repositories, we'll likely find things to clean up or bugs to fix.

This is the first commit in the hardened/13-stable/blackhawk feature
branch. Forward-porting to 14-CURRENT and eventual integration of a few
things into the respective master branches (currently:
hardened/current/master and hardened/13-stable/master) will happen once
we work out those finer details. An example of what could be merged into
master is the pkgbase work.

Signed-off-by:	Shawn Webb <shawn.webb@hardenedbsd.org>
Sponsored-by:	BlackhawkNest, Inc

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -143,6 +143,9 @@ dialog_workaround()
 
 f_dprintf "Began Installation at %s" "$( date )"
 
+PKGBASE_INSTALL=$(f_ispkgbase)
+VENDOR_INSTALL=0
+
 rm -rf $BSDINSTALL_TMPETC
 mkdir $BSDINSTALL_TMPETC
 
@@ -153,35 +156,47 @@ trap error SIGINT	# Catch cntrl-C here
 bsdinstall hostname || error "Set hostname failed"
 
 export DISTRIBUTIONS="base.txz kernel.txz"
-if [ -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
+if [ ${PKGBASE_INSTALL} -eq 0 && -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
 	DISTMENU=`awk -F'\t' '!/^(kernel\.txz|base\.txz)/{print $1,$5,$6}' $BSDINSTALL_DISTDIR/MANIFEST`
 	DISTMENU="$(echo ${DISTMENU} | sed -E 's/\.txz//g')"
 
-	if [ -n "$DISTMENU" ]; then
-		exec 3>&1
-		EXTRA_DISTS=$( eval dialog \
-		    --backtitle \"HardenedBSD Installer\" \
-		    --title \"Distribution Select\" --nocancel --separate-output \
-		    --checklist \"Choose optional system components to install:\" \
-		    0 0 0 $DISTMENU \
-		2>&1 1>&3 )
-		for dist in $EXTRA_DISTS; do
-			export DISTRIBUTIONS="$DISTRIBUTIONS $dist.txz"
-		done
-	fi
+	exec 3>&1
+	EXTRA_DISTS=$( eval dialog \
+		--backtitle \"HardenedBSD Installer\" \
+		--title \"Distribution Select\" --nocancel --separate-output \
+		--checklist \"Choose optional system components to install:\" \
+		0 0 0 $DISTMENU \
+	2>&1 1>&3 )
+	for dist in $EXTRA_DISTS; do
+		export DISTRIBUTIONS="$DISTRIBUTIONS $dist.txz"
+	done
 fi
 
-FETCH_DISTRIBUTIONS=""
-for dist in $DISTRIBUTIONS; do
-	if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
-		FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
-	fi
-done
+if [ ${PKGBASE_INSTALL} -eq 0 ]; then
+	LOCAL_DISTRIBUTIONS="MANIFEST"
+	FETCH_DISTRIBUTIONS=""
+	for dist in $DISTRIBUTIONS; do
+		if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
+			FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
+		else
+			LOCAL_DISTRIBUTIONS="$LOCALDISTRIBUTIONS $dist"
+		fi
+	done
 
-if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
-	dialog --backtitle "HardenedBSD Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
-	bsdinstall netconfig || error
-	NETCONFIG_DONE=yes
+	if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
+		dialog --backtitle "HardenedBSD Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
+		bsdinstall netconfig || error
+		NETCONFIG_DONE=yes
+	fi
+
+	if [ -n "$FETCH_DISTRIBUTIONS" ]; then
+		exec 3>&1
+		BSDINSTALL_DISTSITE=$(`dirname $0`/mirrorselect 2>&1 1>&3)
+		MIRROR_BUTTON=$?
+		exec 3>&-
+		test $MIRROR_BUTTON -eq 0 || error "No mirror selected"
+		export $BSDINSTALL_DISTSITE
+	fi
 fi
 
 rm -f $PATH_FSTAB
@@ -334,33 +349,101 @@ case "$PARTMODE" in
 	;;
 esac
 
-if [ -n "$FETCH_DISTRIBUTIONS" ]; then
-	exec 3>&1
-	export BSDINSTALL_DISTDIR=$(`dirname $0`/fetchmissingdists 2>&1 1>&3)
-	FETCH_RESULT=$?
-	exec 3>&-
+if [ ${PKGBASE_INSTALL} -eq 0 && ! -z "$FETCH_DISTRIBUTIONS" ]; then
+	ALL_DISTRIBUTIONS="$DISTRIBUTIONS"
+	WANT_DEBUG=
 
-	[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"
+	BSDINSTALL_FETCHDEST="$BSDINSTALL_CHROOT/usr/freebsd-dist"
+	mkdir -p "$BSDINSTALL_FETCHDEST" || error "Could not create directory $BSDINSTALL_FETCHDEST"
+
+	export DISTRIBUTIONS="$FETCH_DISTRIBUTIONS"
+	# Try to use any existing distfiles
+	if [ -d $BSDINSTALL_DISTDIR ]; then
+		DISTDIR_IS_UNIONFS=1
+		mount_nullfs -o union "$BSDINSTALL_FETCHDEST" "$BSDINSTALL_DISTDIR"
+	else
+		export DISTRIBUTIONS="$FETCH_DISTRIBUTIONS"
+		export BSDINSTALL_DISTDIR="$BSDINSTALL_FETCHDEST"
+	fi
+
+	export FTP_PASSIVE_MODE=YES
+	for _DISTRIBUTION in $DISTRIBUTIONS; do
+		case $_DISTRIBUTION in
+			*-dbg.*)
+				[ -e $BSDINSTALL_DISTDIR/$_DISTRIBUTION ] \
+					&& continue
+				WANT_DEBUG=1
+				DEBUG_LIST="\n$DEBUG_LIST\n$_DISTRIBUTION"
+				;;
+			*)
+				;;
+		esac
+	done
+
+	bsdinstall distfetch
+	rc=$?
+
+	if [ $rc -ne 0 ]; then
+		msg="FAiled to fetch remote distribution"
+		if [ ! -z "$WANT_DEBUG" ]; then
+			DEBUG_LIST="${DEBUG_LIST%%\n}"
+			DEBUG_LIST="${DEBUG_LIST##\n}"
+			msg="$msg\n\nPlease deselect the following distributions"
+			msg="$msg and retry the installation:"
+			msg="$msg\n$DEBUG_LIST"
+		fi
+		error "$msg"
+	fi
+
+	export DISTRIBUTIONS="$ALL_DISTRIBUTIONS"
 fi
-bsdinstall checksum || error "Distribution checksum failed"
-bsdinstall distextract || error "Distribution extract failed"
+
+if [ ${PKGBASE_INSTALL} -eq 0 && ! -z "$LOCAL_DISTRIBUTIONS" ]; then
+	BSDINSTALL_FETCHDEST="$BSDINSTALL_CHROOT/usr/freebsd-dist"j
+	mkdir -p "$BSDINSTALL_FETCHDEST" || error "Could not create directory $BSDINSTALL_FETCHDEST"
+	if [ -d $BSDINSTALL_DISTDIR ]; then
+		DISTDIR_IS_UNIONFS=1
+		mount_nullfs -o union "$BSDINSTALL_FETCHDEST" "$BSDINSTALL_DISTDIR"
+		export BSDINSTALL_DISTDIR="$BSDINSTALL_FETCHDEST"
+	fi
+	env DISTRIBUTIONS="$LOCAL_DISTRIBUTIONS" \
+		BSDINSTALL_DISTSITE="file///usr/freebsd-dist" \
+		bsdinstall distfetch || \
+		error "FAiled to fetch distribution from local media"
+fi
+
+if [ ${PKGBASE_INSTALL} -eq 0 ]; then
+	bsdinstall checksum || error "Distribution checksum failed"
+	bsdinstall distextract || error "Distribution extract failed"
+else
+	bsdinstall pkgbase || error "FAiled to install pkgbase"
+	bsdinstall vendor || error "Failed to install vendor additions"
+fi
 
 # Set up boot loader
 bsdinstall bootconfig || error "Failed to configure bootloader"
 
-bsdinstall rootpass || error "Could not set root password"
+if [ ${VENDOR_INSTALL} -eq 0 ]; then
+	bsdinstall rootpass || error "Could not set root password"
+fi
 
 trap true SIGINT	# This section is optional
 if [ "$NETCONFIG_DONE" != yes ]; then
-	bsdinstall netconfig	# Don't check for errors -- the user may cancel
+	if [ ${VENDOR_INSTALL} -eq 0 ]; then
+		bsdinstall netconfig	# Don't check for errors -- the user may cancel
+	fi
 fi
-bsdinstall time
-bsdinstall services
-bsdinstall hardening
 
-dialog --backtitle "HardenedBSD Installer" --title "Add User Accounts" --yesno \
-    "Would you like to add users to the installed system now?" 0 0 && \
-    bsdinstall adduser
+bsdinstall time
+
+if [ ${VENDOR_INSTALL} -eq 0 ]; then
+	bsdinstall services
+	bsdinstall hardening
+
+	dialog --backtitle "HardenedBSD Installer" --title "Add User Accounts" --yesno \
+		"Would you like to add users to the installed system now?" 0 0 && \
+		bsdinstall adduser
+fi
 
 finalconfig() {
 	exec 3>&1
@@ -415,7 +498,9 @@ finalconfig() {
 }
 
 # Allow user to change his mind
-finalconfig
+if [ ${VENDOR_INSTALL} -eq 0 ]; then
+	finalconfig
+fi
 
 trap error SIGINT	# SIGINT is bad again
 bsdinstall config  || error "Failed to save config"
@@ -424,14 +509,16 @@ if [ ! -z "$BSDINSTALL_FETCHDEST" ]; then
 	rm -rf "$BSDINSTALL_FETCHDEST"
 fi
 
-dialog --backtitle "HardenedBSD Installer" --title "Manual Configuration" \
-    --default-button no --yesno \
-   "The installation is now finished. Before exiting the installer, would you like to open a shell in the new system to make any final manual modifications?" 0 0
-if [ $? -eq 0 ]; then
-	clear
-	echo This shell is operating in a chroot in the new system. \
-	    When finished making configuration changes, type \"exit\".
-	chroot "$BSDINSTALL_CHROOT" /bin/sh 2>&1
+if [ ${VENDOR_INSTALL} -eq 0 ]; then
+	dialog --backtitle "HardenedBSD Installer" --title "Manual Configuration" \
+		--default-button no --yesno \
+		"The installation is now finished. Before exiting the installer, would you like to open a shell in the new system to make any final manual modifications?" 0 0
+	if [ $? -eq 0 ]; then
+		clear
+		echo This shell is operating in a chroot in the new system. \
+			When finished making configuration changes, type \"exit\".
+		chroot "$BSDINSTALL_CHROOT" /bin/sh 2>&1
+	fi
 fi
 
 bsdinstall entropy
